sudo: false
language: java

# skip default "install" command
install: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - GRADLE_ARGS=""
    # Building source and binary distributions takes time, and it does not verify much, so we skip it in CI
    # However we want to validate licenses
    - SKIP_DIST_TASKS="$GRADLE_ARGS -PskipDist :src:licenses:build"
    - ORG_GRADLE_PROJECT_checksumFailOn=build_finish
    - ORG_GRADLE_PROJECT_checksumPrint=true

matrix:
  include:
    - name: Tests with OpenJDK 8 + code coverage
      jdk: openjdk8
      script:
        - xvfb-run ./gradlew $GRADLE_ARGS check createDist javadocAggregate jacocoReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: Tests with OpenJDK 11
      jdk: openjdk11
      addons:
        apt:
          packages:
            - language-pack-fr
      env:
        - TZ=Pacific/Chatham # flips between +12:45 and +13:45
        - LANG=fr_FR.UTF-8
        - LC_ALL=fr_FR.UTF-8
      script:
        # This job verifies headless mode to ensure Apache JMeter is workable in headless as well
        - ./gradlew -Djava.awt.headless=true -Duser.language=fr -Duser.country=FR $SKIP_DIST_TASKS -PskipCheckstyle -PskipSpotless build javadocAggregate createDist
    - name: Tests with OpenJDK 12
      # Might switch to openjdk-ea when https://github.com/gradle/gradle/issues/10248 is fixed
      jdk: openjdk12
      script:
        - xvfb-run ./gradlew $SKIP_DIST_TASKS -PskipCheckstyle -PskipSpotless build createDist
    - name: Tests with OpenJDK 13
      jdk: openjdk13
      script:
        # Should fail as JDK13 is not supported yet by gradle
        - xvfb-run ./gradlew $SKIP_DIST_TASKS -PskipCheckstyle -PskipSpotless build createDist
  allow_failures:
    - jdk: openjdk13
