sudo: false
language: java

# skip default "install" command
install: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - GRADLE_ARGS=""
    # Building source and binary distributions takes time, and it does not verify much, so we skip it in CI
    # However we want to validate licenses
    - SKIP_DIST_TASKS="$GRADLE_ARGS -PskipDist :src:licenses:build"
    - ORG_GRADLE_PROJECT_checksumFailOn=build_finish
    - ORG_GRADLE_PROJECT_checksumPrint=true

matrix:
  include:
    - name: Tests with OpenJDK 8 + code coverage
      jdk: openjdk8
      script:
        - xvfb-run ./gradlew $GRADLE_ARGS check createDist javadocAggregate jacocoReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: Tests with OpenJDK 11
      jdk: openjdk11
      addons:
        apt:
          packages:
            - language-pack-fr
      env:
        - TZ=Pacific/Chatham # flips between +12:45 and +13:45
        - LANG=fr_FR.UTF-8
        - LC_ALL=fr_FR.UTF-8
      script:
        # This job verifies headless mode to ensure Apache JMeter is workable in headless as well
        - ./gradlew -Djava.awt.headless=true -Duser.language=fr -Duser.country=FR $SKIP_DIST_TASKS -PskipCheckstyle -PskipSpotless build javadocAggregate createDist
    # Java 12 is not here because it has been superceeded by Java 13
    # Tests with Java 12 do not surface much new, so Java 11 (LTS) and Java 13 (non-LTS) are enough for "post Java 9" testing
    - name: Tests with OpenJDK 13
      jdk: openjdk13
      script:
        # ./gradlew wrapper task kills license header from gradle-wrapper.properties, so we use grep/echo to update the file
        - grep -v Sha256 gradle/wrapper/gradle-wrapper.properties | grep -v Url > gradle/wrapper/gradle-wrapper.properties2
        - echo 'distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-6.0-20190929230024+0000-bin.zip' >> gradle/wrapper/gradle-wrapper.properties2
        - mv gradle/wrapper/gradle-wrapper.properties2 gradle/wrapper/gradle-wrapper.properties
        - xvfb-run ./gradlew $SKIP_DIST_TASKS -PskipCheckstyle -PskipSpotless build createDist -PchecksumFailOn=never -PchecksumPrint=false
        # Show difference between the new dependencies and old ones. It is expected that new Gradle version might bring new dependencies
        - diff -u checksum.xml build/checksum/checksum.xml || true
  allow_failures:
    - jdk: openjdk13
