name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  windows:
    name: 'Windows (JDK 12)'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 50
    - name: 'Set up JDK 12'
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: 'Test'
      shell: bash
      run: |
        ./gradlew --no-parallel build -x distTar -x signDistTar -x distTarSource -x signDistTarSource

  mac:
    name: 'macOS (JDK 12)'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 50
    - name: 'Set up JDK 12'
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: 'Test'
      run: |
        ./gradlew --no-parallel build -x distTar -x signDistTar -x distTarSource -x signDistTarSource -Dskip.test_TestDNSCacheManager.testWithCustomResolverAnd1Server=true
